/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostPostImage from './PostPostImage';

/**
 * The Post model module.
 * @module model/Post
 * @version 1.0.0
 */
class Post {
    /**
     * Constructs a new <code>Post</code>.
     * @alias module:model/Post
     * @param postImage {module:model/PostPostImage} 
     * @param postTitle {String} 
     * @param postDesc {String} 
     */
    constructor(postImage, postTitle, postDesc) { 
        
        Post.initialize(this, postImage, postTitle, postDesc);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, postImage, postTitle, postDesc) { 
        obj['postImage'] = postImage;
        obj['postTitle'] = postTitle;
        obj['postDesc'] = postDesc;
    }

    /**
     * Constructs a <code>Post</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Post} obj Optional instance to populate.
     * @return {module:model/Post} The populated <code>Post</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Post();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('postImage')) {
                obj['postImage'] = PostPostImage.constructFromObject(data['postImage']);
            }
            if (data.hasOwnProperty('postTitle')) {
                obj['postTitle'] = ApiClient.convertToType(data['postTitle'], 'String');
            }
            if (data.hasOwnProperty('postDesc')) {
                obj['postDesc'] = ApiClient.convertToType(data['postDesc'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Post.prototype['_id'] = undefined;

/**
 * @member {module:model/PostPostImage} postImage
 */
Post.prototype['postImage'] = undefined;

/**
 * @member {String} postTitle
 */
Post.prototype['postTitle'] = undefined;

/**
 * @member {String} postDesc
 */
Post.prototype['postDesc'] = undefined;






export default Post;

